import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';

import 'generated/messages_all.dart';

// ignore: non_constant_identifier_names
final AppLocalizations app_localizations = AppLocalizations();

/// ````
/// Generated by flutter_intl
/// DO NOT EDIT BY HAND
/// ```
class AppLocalizations {
  static Future<AppLocalizations> load(Locale locale) {
    final String name =
        locale.countryCode == null || locale.countryCode!.isEmpty
            ? locale.languageCode
            : '${locale.languageCode}_${locale.countryCode}';
    final String localeName = Intl.canonicalizedLocale(name);

    return initializeMessages(localeName).then((bool _) {
      Intl.defaultLocale = localeName;
      return AppLocalizations();
    });
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  String get about => Intl.message('about', name: 'about');
  String get addAnAnswer => Intl.message('addAnAnswer', name: 'addAnAnswer');
  String get agreeAndContinue =>
      Intl.message('agreeAndContinue', name: 'agreeAndContinue');
  String answerNumber(int i) =>
      Intl.message('answerNumber', name: 'answerNumber', args: [i + 1]);
  String get arLens => Intl.message('arLens', name: 'arLens');
  String get attachSystemLog =>
      Intl.message('attachSystemLog', name: 'attachSystemLog');
  String get aWordPhraseOrTag =>
      Intl.message('aWordPhraseOrTag', name: 'aWordPhraseOrTag');
  String get block => Intl.message('block', name: 'block');
  String blockAuthor(String author) =>
      Intl.message('blockAuthor', name: 'blockAuthor', args: [author]);
  String get buildDetailsCopied =>
      Intl.message('buildDetailsCopied', name: 'buildDetailsCopied');
  String get bullet => Intl.message('bullet', name: 'bullet');
  String get cancel => Intl.message('cancel', name: 'cancel');
  String get change => Intl.message('change', name: 'change');
  String get changeEmail => Intl.message('changeEmail', name: 'changeEmail');
  String get checkKyronReachable =>
      Intl.message('checkKyronReachable', name: 'checkKyronReachable');
  String get checkEmailConfirm =>
      Intl.message('checkEmailConfirm', name: 'checkEmailConfirm');
  String closeCommunity(String communityName) => Intl.message(
        'closeCommunity',
        name: 'closeCommunity',
        args: [communityName],
      );
  String get closeIt => Intl.message('closeIt', name: 'closeIt');
  String get closeThisCommunity =>
      Intl.message('closeThisCommunity', name: 'closeThisCommunity');
  String get confirmPassword =>
      Intl.message('confirmPassword', name: 'confirmPassword');
  String get contactSupport =>
      Intl.message('contactSupport', name: 'contactSupport');
  String get continueWithEmail =>
      Intl.message('continueWithEmail', name: 'continueWithEmail');
  String get copy => Intl.message('copy', name: 'copy');
  String get copyReportInstead =>
      Intl.message('copyReportInstead', name: 'copyReportInstead');
  String couldNotOpenGoogleSignIn(String error) => Intl.message(
        'couldNotOpenGoogleSignIn',
        name: 'couldNotOpenGoogleSignIn',
        args: [error],
      );
  String couldNotSignOut(String error) =>
      Intl.message('couldNotSignOut', name: 'couldNotSignOut', args: [error]);
  String get couldNotTakePicture =>
      Intl.message('couldNotTakePicture', name: 'couldNotTakePicture');
  String get create => Intl.message('create', name: 'create');
  String get createAccount =>
      Intl.message('createAccount', name: 'createAccount');
  String get createYourAccount =>
      Intl.message('createYourAccount', name: 'createYourAccount');
  String get createYourProfile =>
      Intl.message('createYourProfile', name: 'createYourProfile');
  String get delete => Intl.message('delete', name: 'delete');
  String get deleteThisComment =>
      Intl.message('deleteThisComment', name: 'deleteThisComment');
  String get deleteThisPost =>
      Intl.message('deleteThisPost', name: 'deleteThisPost');
  String get describeAttachment =>
      Intl.message('describeAttachment', name: 'describeAttachment');
  String get description => Intl.message('description', name: 'description');
  String get didCopied => Intl.message('didCopied', name: 'didCopied');
  String get done => Intl.message('done', name: 'done');
  String get drafts => Intl.message('drafts', name: 'drafts');
  String get editProfile => Intl.message('editProfile', name: 'editProfile');
  String get emailNotifications =>
      Intl.message('emailNotifications', name: 'emailNotifications');
  String get faceTrackingUnavailable =>
      Intl.message('faceTrackingUnavailable', name: 'faceTrackingUnavailable');
  String get followers => Intl.message('followers', name: 'followers');
  String get following => Intl.message('following', name: 'following');
  String get forgotPassword =>
      Intl.message('forgotPassword', name: 'forgotPassword');
  String get guidesAndAnswers =>
      Intl.message('guidesAndAnswers', name: 'guidesAndAnswers');
  String get handle => Intl.message('handle', name: 'handle');
  String get helpCentre => Intl.message('helpCentre', name: 'helpCentre');
  String get helpAndSupport =>
      Intl.message('helpAndSupport', name: 'helpAndSupport');
  String get inOneLine => Intl.message('inOneLine', name: 'inOneLine');
  String get itDisappearsForBoth =>
      Intl.message('itDisappearsForBoth', name: 'itDisappearsForBoth');
  String get itWillBeRemoved =>
      Intl.message('itWillBeRemoved', name: 'itWillBeRemoved');
  String get keepEditing => Intl.message('keepEditing', name: 'keepEditing');
  String get kyron => Intl.message('kyron', name: 'kyron');
  String get lagosDesign => Intl.message('lagosDesign', name: 'lagosDesign');
  String get leave => Intl.message('leave', name: 'leave');
  String leaveCommunity(String communityName) => Intl.message(
        'leaveCommunity',
        name: 'leaveCommunity',
        args: [communityName],
      );
  String get letBackIn => Intl.message('letBackIn', name: 'letBackIn');
  String get loadMore => Intl.message('loadMore', name: 'loadMore');
  String get logCleared => Intl.message('logCleared', name: 'logCleared');
  String get logCopied => Intl.message('logCopied', name: 'logCopied');
  String get logIn => Intl.message('logIn', name: 'logIn');
  String get logOut => Intl.message('logOut', name: 'logOut');
  String get logOutQuestion =>
      Intl.message('logOutQuestion', name: 'logOutQuestion');
  String get message => Intl.message('message', name: 'message');
  String get mute => Intl.message('mute', name: 'mute');
  String get mutedAndBlocked =>
      Intl.message('mutedAndBlocked', name: 'mutedAndBlocked');
  String get mutedWordsAndTags =>
      Intl.message('mutedWordsAndTags', name: 'mutedWordsAndTags');
  String get name => Intl.message('name', name: 'name');
  String get nameScreen => Intl.message('nameScreen', name: 'nameScreen');
  String get newEmailAddress =>
      Intl.message('newEmailAddress', name: 'newEmailAddress');
  String get newPassword => Intl.message('newPassword', name: 'newPassword');
  String get newPost => Intl.message('newPost', name: 'newPost');
  String get nothingToCopy =>
      Intl.message('nothingToCopy', name: 'nothingToCopy');
  String get notifications =>
      Intl.message('notifications', name: 'notifications');
  String get notNow => Intl.message('notNow', name: 'notNow');
  String get notSentTapRetry =>
      Intl.message('notSentTapRetry', name: 'notSentTapRetry');
  String get openInBrowser =>
      Intl.message('openInBrowser', name: 'openInBrowser');
  String get pageNotFound => Intl.message('pageNotFound', name: 'pageNotFound');
  String get pickYourInterests =>
      Intl.message('pickYourInterests', name: 'pickYourInterests');
  String get post => Intl.message('post', name: 'post');
  String get postAnalytics =>
      Intl.message('postAnalytics', name: 'postAnalytics');
  String postInCommunity(String communityName) => Intl.message(
        'postInCommunity',
        name: 'postInCommunity',
        args: [communityName],
      );
  String get postTextCopied =>
      Intl.message('postTextCopied', name: 'postTextCopied');
  String get profileUpdated =>
      Intl.message('profileUpdated', name: 'profileUpdated');
  String get pushNotifications =>
      Intl.message('pushNotifications', name: 'pushNotifications');
  String get quote => Intl.message('quote', name: 'quote');
  String get quotePost => Intl.message('quotePost', name: 'quotePost');
  String get reachAPerson => Intl.message('reachAPerson', name: 'reachAPerson');
  String get remove => Intl.message('remove', name: 'remove');
  String removeMember(String memberName) =>
      Intl.message('removeMember', name: 'removeMember', args: [memberName]);
  String get removeConversation =>
      Intl.message('removeConversation', name: 'removeConversation');
  String get removeMessage =>
      Intl.message('removeMessage', name: 'removeMessage');
  String get repliesFollowsMentions =>
      Intl.message('repliesFollowsMentions', name: 'repliesFollowsMentions');
  String get reply => Intl.message('reply', name: 'reply');
  String get report => Intl.message('report', name: 'report');
  String get reportCopied => Intl.message('reportCopied', name: 'reportCopied');
  String get reportSent => Intl.message('reportSent', name: 'reportSent');
  String get repost => Intl.message('repost', name: 'repost');
  String get reset => Intl.message('reset', name: 'reset');
  String get resetPassword =>
      Intl.message('resetPassword', name: 'resetPassword');
  String get retry => Intl.message('retry', name: 'retry');
  String get save => Intl.message('save', name: 'save');
  String get saveDraft => Intl.message('saveDraft', name: 'saveDraft');
  String saySomething(String communityName) =>
      Intl.message('saySomething', name: 'saySomething', args: [communityName]);
  String get searchByNameOrHandle =>
      Intl.message('searchByNameOrHandle', name: 'searchByNameOrHandle');
  String get searchCommunities =>
      Intl.message('searchCommunities', name: 'searchCommunities');
  String get searchGIFs => Intl.message('searchGIFs', name: 'searchGIFs');
  String get searchLanguages =>
      Intl.message('searchLanguages', name: 'searchLanguages');
  String get searchTrendingTags =>
      Intl.message('searchTrendingTags', name: 'searchTrendingTags');
  String get securityAlerts =>
      Intl.message('securityAlerts', name: 'securityAlerts');
  String get sendConfirmation =>
      Intl.message('sendConfirmation', name: 'sendConfirmation');
  String get sendErrorReport =>
      Intl.message('sendErrorReport', name: 'sendErrorReport');
  String get sendFeedback => Intl.message('sendFeedback', name: 'sendFeedback');
  String get sendReport => Intl.message('sendReport', name: 'sendReport');
  String get sendToSupport =>
      Intl.message('sendToSupport', name: 'sendToSupport');
  String get serviceStatus =>
      Intl.message('serviceStatus', name: 'serviceStatus');
  String get shareAppLog => Intl.message('shareAppLog', name: 'shareAppLog');
  String get signedInAs => Intl.message('signedInAs', name: 'signedInAs');
  String get signInToKyron =>
      Intl.message('signInToKyron', name: 'signInToKyron');
  String signupFailed(String error) =>
      Intl.message('signupFailed', name: 'signupFailed', args: [error]);
  String get stay => Intl.message('stay', name: 'stay');
  String get systemLog => Intl.message('systemLog', name: 'systemLog');
  String get tellMissingBroken =>
      Intl.message('tellMissingBroken', name: 'tellMissingBroken');
  String get theComposerNoPostButton =>
      Intl.message('theComposerNoPostButton', name: 'theComposerNoPostButton');
  String get translate => Intl.message('translate', name: 'translate');
  String get tryAgain => Intl.message('tryAgain', name: 'tryAgain');
  String get undoRepost => Intl.message('undoRepost', name: 'undoRepost');
  String get updatePassword =>
      Intl.message('updatePassword', name: 'updatePassword');
  String get useDifferentAddress =>
      Intl.message('useDifferentAddress', name: 'useDifferentAddress');
  String get whatHappened => Intl.message('whatHappened', name: 'whatHappened');
  String get whatHappenedAndLookAt =>
      Intl.message('whatHappenedAndLookAt', name: 'whatHappenedAndLookAt');
  String get whatInPicture =>
      Intl.message('whatInPicture', name: 'whatInPicture');
  String get whatIsItFor => Intl.message('whatIsItFor', name: 'whatIsItFor');
  String get whatYouDid => Intl.message('whatYouDid', name: 'whatYouDid');
  String get whatYouWereDoing =>
      Intl.message('whatYouWereDoing', name: 'whatYouWereDoing');
  String get normalised => Intl.message('normalised', name: 'normalised');

  String get postItSayItShowIt => Intl.message('postItSayItShowIt', name: 'postItSayItShowIt');
  String get textVoiceVideoPeopleRooms => Intl.message('textVoiceVideoPeopleRooms', name: 'textVoiceVideoPeopleRooms');
  String get alreadyOnKyron => Intl.message('alreadyOnKyron', name: 'alreadyOnKyron');
  String get byContinuingAgreeTermsPrivacy => Intl.message('byContinuingAgreeTermsPrivacy', name: 'byContinuingAgreeTermsPrivacy');
  String get byContinuingAgreeTerms => Intl.message('byContinuingAgreeTerms', name: 'byContinuingAgreeTerms');
  String get googleSignInNeedsPhoneApp => Intl.message('googleSignInNeedsPhoneApp', name: 'googleSignInNeedsPhoneApp');
  String googleSignInDesktopExplanation(String platform) => Intl.message('googleSignInDesktopExplanation', name: 'googleSignInDesktopExplanation', args: [platform]);
  String get loginFailed => Intl.message('loginFailed', name: 'loginFailed');
  String get email => Intl.message('email', name: 'email');
  String get password => Intl.message('password', name: 'password');
  String get login => Intl.message('login', name: 'login');
  String get or => Intl.message('or', name: 'or');
  String get username => Intl.message('username', name: 'username');
  String get usernameRule => Intl.message('usernameRule', name: 'usernameRule');
  String get passwordTooShort => Intl.message('passwordTooShort', name: 'passwordTooShort');
  String get continueAction => Intl.message('continueAction', name: 'continueAction');
  String get bySigningUpAgreeTerms => Intl.message('bySigningUpAgreeTerms', name: 'bySigningUpAgreeTerms');
  String get terms => Intl.message('terms', name: 'terms');
  String get and => Intl.message('and', name: 'and');
  String get privacyPolicy => Intl.message('privacyPolicy', name: 'privacyPolicy');
  String get googleSignIn => Intl.message('googleSignIn', name: 'googleSignIn');
  String get googleSignUp => Intl.message('googleSignUp', name: 'googleSignUp');
  String get googleContinue => Intl.message('googleContinue', name: 'googleContinue');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  List<Locale> get supportedLocales => const [Locale('en'), Locale('es')];

  @override
  bool isSupported(Locale locale) => ['en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
