import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';

import 'generated/messages_all.dart';

// ignore: non_constant_identifier_names
final AppLocalizations app_localizations = AppLocalizations();

/// ````
/// Generated by flutter_intl
/// DO NOT EDIT BY HAND
/// ```
class AppLocalizations {
  static Future<AppLocalizations> load(Locale locale) {
    final String name =
        locale.countryCode == null || locale.countryCode!.isEmpty
            ? locale.languageCode
            : '${locale.languageCode}_${locale.countryCode}';
    final String localeName = Intl.canonicalizedLocale(name);

    return initializeMessages(localeName).then((bool _) {
      Intl.defaultLocale = localeName;
      return AppLocalizations();
    });
  }

  static AppLocalizations of(BuildContext context) {
    // Keep lightweight widget trees (including tests and embedded surfaces)
    // usable when they do not install the app's full localization delegates.
    final localized = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    if (localized != null) return localized;

    // The generated message lookup is registered synchronously before the
    // returned future completes, which makes the English fallback available
    // during the same build that first asks for it.
    // A tree without a delegate is an English-only lightweight tree. Do not
    // let a previous localized test or an unrelated widget change the global
    // Intl locale underneath it.
    Intl.defaultLocale = 'en';
    initializeMessages('en');
    return app_localizations;
  }

  /// Looks up UI copy added to the ARB catalogs without requiring a generated
  /// Dart accessor for every short label. The fallback is also the English
  /// source value, so older generated catalogs remain safe until regenerated.
  String ui(String key, String fallback) => Intl.message(fallback, name: key);
  String authorPostsHidden(String author) => Intl.message(
        'You will not see posts from $author',
        name: 'authorPostsHidden',
        args: [author],
      );
  String authorBlocked(String author) => Intl.message(
        '$author blocked',
        name: 'authorBlocked',
        args: [author],
      );
  String nothingMatchesQuery(String what) => Intl.message(
        'Nothing on Kyron matches "$what"',
        name: 'nothingMatchesQuery',
        args: [what],
      );
  String repliesPolicy(String policy) => Intl.message(
        'Replies: $policy',
        name: 'repliesPolicy',
        args: [policy],
      );
  String feedTagDetail(String tab) => Intl.message(
        'Nothing has been posted under #$tab yet.',
        name: 'feedTagDetail',
        args: [tab],
      );
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  String get about => Intl.message('about', name: 'about');
  String get addAnAnswer => Intl.message('addAnAnswer', name: 'addAnAnswer');
  String get agreeAndContinue =>
      Intl.message('agreeAndContinue', name: 'agreeAndContinue');
  String answerNumber(int i) =>
      Intl.message('answerNumber', name: 'answerNumber', args: [i + 1]);
  String get arLens => Intl.message('arLens', name: 'arLens');
  String get attachSystemLog =>
      Intl.message('attachSystemLog', name: 'attachSystemLog');
  String get aWordPhraseOrTag =>
      Intl.message('aWordPhraseOrTag', name: 'aWordPhraseOrTag');
  String get block => Intl.message('block', name: 'block');
  String blockAuthor(String author) =>
      Intl.message('blockAuthor', name: 'blockAuthor', args: [author]);
  String get buildDetailsCopied =>
      Intl.message('buildDetailsCopied', name: 'buildDetailsCopied');
  String get bullet => Intl.message('bullet', name: 'bullet');
  String get cancel => Intl.message('cancel', name: 'cancel');
  String get change => Intl.message('change', name: 'change');
  String get changeEmail => Intl.message('changeEmail', name: 'changeEmail');
  String get checkKyronReachable =>
      Intl.message('checkKyronReachable', name: 'checkKyronReachable');
  String get checkEmailConfirm =>
      Intl.message('checkEmailConfirm', name: 'checkEmailConfirm');
  String closeCommunity(String communityName) => Intl.message(
        'closeCommunity',
        name: 'closeCommunity',
        args: [communityName],
      );
  String get closeIt => Intl.message('closeIt', name: 'closeIt');
  String get closeThisCommunity =>
      Intl.message('closeThisCommunity', name: 'closeThisCommunity');
  String get confirmPassword =>
      Intl.message('confirmPassword', name: 'confirmPassword');
  String get contactSupport =>
      Intl.message('contactSupport', name: 'contactSupport');
  String get continueWithEmail =>
      Intl.message('continueWithEmail', name: 'continueWithEmail');
  String get copy => Intl.message('copy', name: 'copy');
  String get copyReportInstead =>
      Intl.message('copyReportInstead', name: 'copyReportInstead');
  String couldNotOpenGoogleSignIn(String error) => Intl.message(
        'couldNotOpenGoogleSignIn',
        name: 'couldNotOpenGoogleSignIn',
        args: [error],
      );
  String couldNotSignOut(String error) =>
      Intl.message('couldNotSignOut', name: 'couldNotSignOut', args: [error]);
  String get couldNotTakePicture =>
      Intl.message('couldNotTakePicture', name: 'couldNotTakePicture');
  String get create => Intl.message('create', name: 'create');
  String get createAccount =>
      Intl.message('createAccount', name: 'createAccount');
  String get createYourAccount =>
      Intl.message('createYourAccount', name: 'createYourAccount');
  String get createYourProfile =>
      Intl.message('createYourProfile', name: 'createYourProfile');
  String get delete => Intl.message('delete', name: 'delete');
  String get deleteThisComment =>
      Intl.message('deleteThisComment', name: 'deleteThisComment');
  String get deleteThisPost =>
      Intl.message('deleteThisPost', name: 'deleteThisPost');
  String get describeAttachment =>
      Intl.message('describeAttachment', name: 'describeAttachment');
  String get description => Intl.message('description', name: 'description');
  String get didCopied => Intl.message('didCopied', name: 'didCopied');
  String get done => Intl.message('done', name: 'done');
  String get drafts => Intl.message('drafts', name: 'drafts');
  String get editProfile => Intl.message('editProfile', name: 'editProfile');
  String get emailNotifications =>
      Intl.message('emailNotifications', name: 'emailNotifications');
  String get faceTrackingUnavailable =>
      Intl.message('faceTrackingUnavailable', name: 'faceTrackingUnavailable');
  String get followers => Intl.message('followers', name: 'followers');
  String get following => Intl.message('following', name: 'following');
  String get forgotPassword =>
      Intl.message('forgotPassword', name: 'forgotPassword');
  String get guidesAndAnswers =>
      Intl.message('guidesAndAnswers', name: 'guidesAndAnswers');
  String get handle => Intl.message('handle', name: 'handle');
  String get helpCentre => Intl.message('helpCentre', name: 'helpCentre');
  String get helpAndSupport =>
      Intl.message('helpAndSupport', name: 'helpAndSupport');
  String get inOneLine => Intl.message('inOneLine', name: 'inOneLine');
  String get itDisappearsForBoth =>
      Intl.message('itDisappearsForBoth', name: 'itDisappearsForBoth');
  String get itWillBeRemoved =>
      Intl.message('itWillBeRemoved', name: 'itWillBeRemoved');
  String get keepEditing => Intl.message('keepEditing', name: 'keepEditing');
  String get kyron => Intl.message('kyron', name: 'kyron');
  String get lagosDesign => Intl.message('lagosDesign', name: 'lagosDesign');
  String get leave => Intl.message('leave', name: 'leave');
  String leaveCommunity(String communityName) => Intl.message(
        'leaveCommunity',
        name: 'leaveCommunity',
        args: [communityName],
      );
  String get letBackIn => Intl.message('letBackIn', name: 'letBackIn');
  String get loadMore => Intl.message('loadMore', name: 'loadMore');
  String get logCleared => Intl.message('logCleared', name: 'logCleared');
  String get logCopied => Intl.message('logCopied', name: 'logCopied');
  String get logIn => Intl.message('logIn', name: 'logIn');
  String get logOut => Intl.message('logOut', name: 'logOut');
  String get logOutQuestion =>
      Intl.message('logOutQuestion', name: 'logOutQuestion');
  String get message => Intl.message('message', name: 'message');
  String get mute => Intl.message('mute', name: 'mute');
  String get mutedAndBlocked =>
      Intl.message('mutedAndBlocked', name: 'mutedAndBlocked');
  String get mutedWordsAndTags =>
      Intl.message('mutedWordsAndTags', name: 'mutedWordsAndTags');
  String get name => Intl.message('name', name: 'name');
  String get nameScreen => Intl.message('nameScreen', name: 'nameScreen');
  String get newEmailAddress =>
      Intl.message('newEmailAddress', name: 'newEmailAddress');
  String get newPassword => Intl.message('newPassword', name: 'newPassword');
  String get newPost => Intl.message('newPost', name: 'newPost');
  String get nothingToCopy =>
      Intl.message('nothingToCopy', name: 'nothingToCopy');
  String get notifications =>
      Intl.message('notifications', name: 'notifications');
  String get notNow => Intl.message('notNow', name: 'notNow');
  String get notSentTapRetry =>
      Intl.message('notSentTapRetry', name: 'notSentTapRetry');
  String get openInBrowser =>
      Intl.message('openInBrowser', name: 'openInBrowser');
  String get pageNotFound => Intl.message('pageNotFound', name: 'pageNotFound');
  String get pickYourInterests =>
      Intl.message('pickYourInterests', name: 'pickYourInterests');
  String get post => Intl.message('post', name: 'post');
  String get postAnalytics =>
      Intl.message('postAnalytics', name: 'postAnalytics');
  String postInCommunity(String communityName) => Intl.message(
        'postInCommunity',
        name: 'postInCommunity',
        args: [communityName],
      );
  String get postTextCopied =>
      Intl.message('postTextCopied', name: 'postTextCopied');
  String get profileUpdated =>
      Intl.message('profileUpdated', name: 'profileUpdated');
  String get pushNotifications =>
      Intl.message('pushNotifications', name: 'pushNotifications');
  String get quote => Intl.message('quote', name: 'quote');
  String get quotePost => Intl.message('quotePost', name: 'quotePost');
  String get reachAPerson => Intl.message('reachAPerson', name: 'reachAPerson');
  String get remove => Intl.message('remove', name: 'remove');
  String removeMember(String memberName) =>
      Intl.message('removeMember', name: 'removeMember', args: [memberName]);
  String get removeConversation =>
      Intl.message('removeConversation', name: 'removeConversation');
  String get removeMessage =>
      Intl.message('removeMessage', name: 'removeMessage');
  String get repliesFollowsMentions =>
      Intl.message('repliesFollowsMentions', name: 'repliesFollowsMentions');
  String get reply => Intl.message('reply', name: 'reply');
  String get report => Intl.message('report', name: 'report');
  String get reportCopied => Intl.message('reportCopied', name: 'reportCopied');
  String get reportSent => Intl.message('reportSent', name: 'reportSent');
  String get repost => Intl.message('repost', name: 'repost');
  String get reset => Intl.message('reset', name: 'reset');
  String get resetPassword =>
      Intl.message('resetPassword', name: 'resetPassword');
  String get retry => Intl.message('retry', name: 'retry');
  String get save => Intl.message('save', name: 'save');
  String get saveDraft => Intl.message('saveDraft', name: 'saveDraft');
  String saySomething(String communityName) =>
      Intl.message('saySomething', name: 'saySomething', args: [communityName]);
  String get searchByNameOrHandle =>
      Intl.message('searchByNameOrHandle', name: 'searchByNameOrHandle');
  String get searchCommunities =>
      Intl.message('searchCommunities', name: 'searchCommunities');
  String get searchGIFs => Intl.message('searchGIFs', name: 'searchGIFs');
  String get searchLanguages =>
      Intl.message('searchLanguages', name: 'searchLanguages');
  String get searchTrendingTags =>
      Intl.message('searchTrendingTags', name: 'searchTrendingTags');
  String get securityAlerts =>
      Intl.message('securityAlerts', name: 'securityAlerts');
  String get sendConfirmation =>
      Intl.message('sendConfirmation', name: 'sendConfirmation');
  String get sendErrorReport =>
      Intl.message('sendErrorReport', name: 'sendErrorReport');
  String get sendFeedback => Intl.message('sendFeedback', name: 'sendFeedback');
  String get sendReport => Intl.message('sendReport', name: 'sendReport');
  String get sendToSupport =>
      Intl.message('sendToSupport', name: 'sendToSupport');
  String get serviceStatus =>
      Intl.message('serviceStatus', name: 'serviceStatus');
  String get shareAppLog => Intl.message('shareAppLog', name: 'shareAppLog');
  String get signedInAs => Intl.message('signedInAs', name: 'signedInAs');
  String get signInToKyron =>
      Intl.message('signInToKyron', name: 'signInToKyron');
  String signupFailed(String error) =>
      Intl.message('signupFailed', name: 'signupFailed', args: [error]);
  String get stay => Intl.message('stay', name: 'stay');
  String get systemLog => Intl.message('systemLog', name: 'systemLog');
  String get tellMissingBroken =>
      Intl.message('tellMissingBroken', name: 'tellMissingBroken');
  String get theComposerNoPostButton =>
      Intl.message('theComposerNoPostButton', name: 'theComposerNoPostButton');
  String get translate => Intl.message('translate', name: 'translate');
  String get tryAgain => Intl.message('tryAgain', name: 'tryAgain');
  String get undoRepost => Intl.message('undoRepost', name: 'undoRepost');
  String get updatePassword =>
      Intl.message('updatePassword', name: 'updatePassword');
  String get useDifferentAddress =>
      Intl.message('useDifferentAddress', name: 'useDifferentAddress');
  String get whatHappened => Intl.message('whatHappened', name: 'whatHappened');
  String get whatHappenedAndLookAt =>
      Intl.message('whatHappenedAndLookAt', name: 'whatHappenedAndLookAt');
  String get whatInPicture =>
      Intl.message('whatInPicture', name: 'whatInPicture');
  String get whatIsItFor => Intl.message('whatIsItFor', name: 'whatIsItFor');
  String get whatYouDid => Intl.message('whatYouDid', name: 'whatYouDid');
  String get whatYouWereDoing =>
      Intl.message('whatYouWereDoing', name: 'whatYouWereDoing');
  String get normalised => Intl.message('normalised', name: 'normalised');

  String get postItSayItShowIt =>
      Intl.message('postItSayItShowIt', name: 'postItSayItShowIt');
  String get textVoiceVideoPeopleRooms => Intl.message(
        'textVoiceVideoPeopleRooms',
        name: 'textVoiceVideoPeopleRooms',
      );
  String get alreadyOnKyron =>
      Intl.message('alreadyOnKyron', name: 'alreadyOnKyron');
  String get byContinuingAgreeTermsPrivacy => Intl.message(
        'byContinuingAgreeTermsPrivacy',
        name: 'byContinuingAgreeTermsPrivacy',
      );
  String get byContinuingAgreeTerms =>
      Intl.message('byContinuingAgreeTerms', name: 'byContinuingAgreeTerms');
  String get googleSignInNeedsPhoneApp => Intl.message(
        'googleSignInNeedsPhoneApp',
        name: 'googleSignInNeedsPhoneApp',
      );
  String googleSignInDesktopExplanation(String platform) => Intl.message(
        'googleSignInDesktopExplanation',
        name: 'googleSignInDesktopExplanation',
        args: [platform],
      );
  String get loginFailed => Intl.message('loginFailed', name: 'loginFailed');
  String get email => Intl.message('email', name: 'email');
  String get password => Intl.message('password', name: 'password');
  String get login => Intl.message('login', name: 'login');
  String get or => Intl.message('or', name: 'or');
  String get username => Intl.message('username', name: 'username');
  String get usernameRule => Intl.message('usernameRule', name: 'usernameRule');
  String get passwordTooShort =>
      Intl.message('passwordTooShort', name: 'passwordTooShort');
  String get continueAction =>
      Intl.message('continueAction', name: 'continueAction');
  String get bySigningUpAgreeTerms =>
      Intl.message('bySigningUpAgreeTerms', name: 'bySigningUpAgreeTerms');
  String get terms => Intl.message('terms', name: 'terms');
  String get and => Intl.message('and', name: 'and');
  String get privacyPolicy =>
      Intl.message('privacyPolicy', name: 'privacyPolicy');
  String get googleSignIn => Intl.message('googleSignIn', name: 'googleSignIn');
  String get googleSignUp => Intl.message('googleSignUp', name: 'googleSignUp');
  String get googleContinue =>
      Intl.message('googleContinue', name: 'googleContinue');
  String get literalwhetherKyronIsReachableRightNow => Intl.message(
        'literalwhetherKyronIsReachableRightNow',
        name: 'literalwhetherKyronIsReachableRightNow',
      );
  String get literalwhatThisAppHasBeenDoing => Intl.message(
        'literalwhatThisAppHasBeenDoing',
        name: 'literalwhatThisAppHasBeenDoing',
      );
  String get literalshareTheLogWithSupport => Intl.message(
        'literalshareTheLogWithSupport',
        name: 'literalshareTheLogWithSupport',
      );
  String get literalclearCache =>
      Intl.message('literalclearCache', name: 'literalclearCache');
  String get literalappVersion =>
      Intl.message('literalappVersion', name: 'literalappVersion');
  String get literalreading =>
      Intl.message('literalreading', name: 'literalreading');
  String get literalcheckAgain =>
      Intl.message('literalcheckAgain', name: 'literalcheckAgain');
  String get literalkyronDidNotAnswer => Intl.message(
        'literalkyronDidNotAnswer',
        name: 'literalkyronDidNotAnswer',
      );
  String get literalnothingLoggedYet =>
      Intl.message('literalnothingLoggedYet', name: 'literalnothingLoggedYet');
  String get literalswitchCamera =>
      Intl.message('literalswitchCamera', name: 'literalswitchCamera');
  String get literaltheCameraIsClosed => Intl.message(
        'literaltheCameraIsClosed',
        name: 'literaltheCameraIsClosed',
      );
  String get literaltakeAPicture =>
      Intl.message('literaltakeAPicture', name: 'literaltakeAPicture');
  String literallensNameFaceLens(Object lens) => Intl.message(
        'literallensNameFaceLens',
        name: 'literallensNameFaceLens',
        args: [lens],
      );
  String get literalcouldNotPostThatReply => Intl.message(
        'literalcouldNotPostThatReply',
        name: 'literalcouldNotPostThatReply',
      );
  String get literalcouldNotLoadThisReply => Intl.message(
        'literalcouldNotLoadThisReply',
        name: 'literalcouldNotLoadThisReply',
      );
  String get literalthisReplyIsGone =>
      Intl.message('literalthisReplyIsGone', name: 'literalthisReplyIsGone');
  String get literaladdAPhoto =>
      Intl.message('literaladdAPhoto', name: 'literaladdAPhoto');
  String get literaladdAClip =>
      Intl.message('literaladdAClip', name: 'literaladdAClip');
  String get literalstartACommunity =>
      Intl.message('literalstartACommunity', name: 'literalstartACommunity');
  String get literalcouldNotLoadYourCommunities => Intl.message(
        'literalcouldNotLoadYourCommunities',
        name: 'literalcouldNotLoadYourCommunities',
      );
  String get literalyouAreNotInAnyCommunities => Intl.message(
        'literalyouAreNotInAnyCommunities',
        name: 'literalyouAreNotInAnyCommunities',
      );
  String get literalcouldNotLoadCommunities => Intl.message(
        'literalcouldNotLoadCommunities',
        name: 'literalcouldNotLoadCommunities',
      );
  String literalpostInWidgetCommunityName(Object widget) => Intl.message(
        'literalpostInWidgetCommunityName',
        name: 'literalpostInWidgetCommunityName',
        args: [widget],
      );
  String literalsaySomethingToWidgetCommunityName(Object widget) =>
      Intl.message(
        'literalsaySomethingToWidgetCommunityName',
        name: 'literalsaySomethingToWidgetCommunityName',
        args: [widget],
      );
  String get literaltagSomeone =>
      Intl.message('literaltagSomeone', name: 'literaltagSomeone');
  String literalcloseWidgetCommunityName(Object widget) => Intl.message(
        'literalcloseWidgetCommunityName',
        name: 'literalcloseWidgetCommunityName',
        args: [widget],
      );
  String get literalonlyTheOwnerCanChangeThis => Intl.message(
        'literalonlyTheOwnerCanChangeThis',
        name: 'literalonlyTheOwnerCanChangeThis',
      );
  String get literaltapTheBannerOrThePictureToChangeIt => Intl.message(
        'literaltapTheBannerOrThePictureToChangeIt',
        name: 'literaltapTheBannerOrThePictureToChangeIt',
      );
  String literalremoveMemberDisplayname(Object member) => Intl.message(
        'literalremoveMemberDisplayname',
        name: 'literalremoveMemberDisplayname',
        args: [member],
      );
  String get literalcouldNotLoadTheMembers => Intl.message(
        'literalcouldNotLoadTheMembers',
        name: 'literalcouldNotLoadTheMembers',
      );
  String get literalnobodyHereYet =>
      Intl.message('literalnobodyHereYet', name: 'literalnobodyHereYet');
  String get literalmakeAModerator =>
      Intl.message('literalmakeAModerator', name: 'literalmakeAModerator');
  String get literalremoveAsModerator => Intl.message(
        'literalremoveAsModerator',
        name: 'literalremoveAsModerator',
      );
  String get literalremoveFromCommunity => Intl.message(
        'literalremoveFromCommunity',
        name: 'literalremoveFromCommunity',
      );
  String get literalcouldNotLoadThisList => Intl.message(
        'literalcouldNotLoadThisList',
        name: 'literalcouldNotLoadThisList',
      );
  String get literalnobodyHasBeenRemoved => Intl.message(
        'literalnobodyHasBeenRemoved',
        name: 'literalnobodyHasBeenRemoved',
      );
  String literalpostInCommunityName(Object community) => Intl.message(
        'literalpostInCommunityName',
        name: 'literalpostInCommunityName',
        args: [community],
      );
  String get literalcouldNotOpenThisCommunity => Intl.message(
        'literalcouldNotOpenThisCommunity',
        name: 'literalcouldNotOpenThisCommunity',
      );
  String get literalthisCommunity =>
      Intl.message('literalthisCommunity', name: 'literalthisCommunity');
  String get literalshareThisCommunity => Intl.message(
        'literalshareThisCommunity',
        name: 'literalshareThisCommunity',
      );
  String get literalcopyLink =>
      Intl.message('literalcopyLink', name: 'literalcopyLink');
  String get literallinkCopied =>
      Intl.message('literallinkCopied', name: 'literallinkCopied');
  String literalleaveCommunityName(Object community) => Intl.message(
        'literalleaveCommunityName',
        name: 'literalleaveCommunityName',
        args: [community],
      );
  String literalyouHaveLeftCommunityName(Object community) => Intl.message(
        'literalyouHaveLeftCommunityName',
        name: 'literalyouHaveLeftCommunityName',
        args: [community],
      );
  String get literaladdAVideo =>
      Intl.message('literaladdAVideo', name: 'literaladdAVideo');
  String get literaladdAGif =>
      Intl.message('literaladdAGif', name: 'literaladdAGif');
  String get literalrecordAVoicePost =>
      Intl.message('literalrecordAVoicePost', name: 'literalrecordAVoicePost');
  String get literalremoveThePoll =>
      Intl.message('literalremoveThePoll', name: 'literalremoveThePoll');
  String get literaladdAPoll =>
      Intl.message('literaladdAPoll', name: 'literaladdAPoll');
  String get literaladdAHashtag =>
      Intl.message('literaladdAHashtag', name: 'literaladdAHashtag');
  String get literaldraftSaved =>
      Intl.message('literaldraftSaved', name: 'literaldraftSaved');
  String get literalnoDrafts =>
      Intl.message('literalnoDrafts', name: 'literalnoDrafts');
  String get literalcouldNotLoadTrending => Intl.message(
        'literalcouldNotLoadTrending',
        name: 'literalcouldNotLoadTrending',
      );
  String get literalnothingIsTrendingYet => Intl.message(
        'literalnothingIsTrendingYet',
        name: 'literalnothingIsTrendingYet',
      );
  String get literalcouldNotLoadTopics => Intl.message(
        'literalcouldNotLoadTopics',
        name: 'literalcouldNotLoadTopics',
      );
  String get literalnoTopicsYet =>
      Intl.message('literalnoTopicsYet', name: 'literalnoTopicsYet');
  String get literalcouldNotLoadSuggestions => Intl.message(
        'literalcouldNotLoadSuggestions',
        name: 'literalcouldNotLoadSuggestions',
      );
  String get literalnobodyLeftToSuggest => Intl.message(
        'literalnobodyLeftToSuggest',
        name: 'literalnobodyLeftToSuggest',
      );
  String get literalyouExampleCom =>
      Intl.message('literalyouExampleCom', name: 'literalyouExampleCom');
  String get literalsendTheLink =>
      Intl.message('literalsendTheLink', name: 'literalsendTheLink');
  String get literalopenTheMailFromKyron => Intl.message(
        'literalopenTheMailFromKyron',
        name: 'literalopenTheMailFromKyron',
      );
  String get literaltapTheLinkInsideIt => Intl.message(
        'literaltapTheLinkInsideIt',
        name: 'literaltapTheLinkInsideIt',
      );
  String get literalsetAPasswordAndCarryOn => Intl.message(
        'literalsetAPasswordAndCarryOn',
        name: 'literalsetAPasswordAndCarryOn',
      );
  String literalsendAgainInCooldownS(Object _cooldown) => Intl.message(
        'literalsendAgainInCooldownS',
        name: 'literalsendAgainInCooldownS',
        args: [_cooldown],
      );
  String get literalsendAgain =>
      Intl.message('literalsendAgain', name: 'literalsendAgain');
  String literalnormalised(Object normalised) => Intl.message(
        'literalnormalised',
        name: 'literalnormalised',
        args: [normalised],
      );
  String get literalcouldNotLoadYourMessages => Intl.message(
        'literalcouldNotLoadYourMessages',
        name: 'literalcouldNotLoadYourMessages',
      );
  String get literalnothingUnread =>
      Intl.message('literalnothingUnread', name: 'literalnothingUnread');
  String get literalnoMessagesYet =>
      Intl.message('literalnoMessagesYet', name: 'literalnoMessagesYet');
  String get literalnothingMuted =>
      Intl.message('literalnothingMuted', name: 'literalnothingMuted');
  String get literalnoLikesYet =>
      Intl.message('literalnoLikesYet', name: 'literalnoLikesYet');
  String get literalnoRepliesYet =>
      Intl.message('literalnoRepliesYet', name: 'literalnoRepliesYet');
  String get literalnoNewFollowers =>
      Intl.message('literalnoNewFollowers', name: 'literalnoNewFollowers');
  String get literalnoRepostsYet =>
      Intl.message('literalnoRepostsYet', name: 'literalnoRepostsYet');
  String get literalyouAreAllCaughtUp => Intl.message(
        'literalyouAreAllCaughtUp',
        name: 'literalyouAreAllCaughtUp',
      );
  String get literalcouldNotLoadNotifications => Intl.message(
        'literalcouldNotLoadNotifications',
        name: 'literalcouldNotLoadNotifications',
      );
  String get literalcoverPhoto =>
      Intl.message('literalcoverPhoto', name: 'literalcoverPhoto');
  String get literalchooseFromGallery => Intl.message(
        'literalchooseFromGallery',
        name: 'literalchooseFromGallery',
      );
  String get literaluseOneOfOurs =>
      Intl.message('literaluseOneOfOurs', name: 'literaluseOneOfOurs');
  String get literaltapToAddAPhotoAndACover => Intl.message(
        'literaltapToAddAPhotoAndACover',
        name: 'literaltapToAddAPhotoAndACover',
      );
  String get literalnoInterestsYet =>
      Intl.message('literalnoInterestsYet', name: 'literalnoInterestsYet');
  String get literaldiscoverPeople =>
      Intl.message('literaldiscoverPeople', name: 'literaldiscoverPeople');
  String get literalcancelReply =>
      Intl.message('literalcancelReply', name: 'literalcancelReply');
  String get literalcouldNotLoadThisPost => Intl.message(
        'literalcouldNotLoadThisPost',
        name: 'literalcouldNotLoadThisPost',
      );
  String get literalshareThisProfile =>
      Intl.message('literalshareThisProfile', name: 'literalshareThisProfile');
  String get literalcouldNotLoadThesePosts => Intl.message(
        'literalcouldNotLoadThesePosts',
        name: 'literalcouldNotLoadThesePosts',
      );
  String get literalyouHaveNotPostedYet => Intl.message(
        'literalyouHaveNotPostedYet',
        name: 'literalyouHaveNotPostedYet',
      );
  String get literalnoPostsYet =>
      Intl.message('literalnoPostsYet', name: 'literalnoPostsYet');
  String get literalnothingToLookAtYet => Intl.message(
        'literalnothingToLookAtYet',
        name: 'literalnothingToLookAtYet',
      );
  String get literalkeepTyping =>
      Intl.message('literalkeepTyping', name: 'literalkeepTyping');
  String get literalsearchFailed =>
      Intl.message('literalsearchFailed', name: 'literalsearchFailed');
  String get literalnothingMatched =>
      Intl.message('literalnothingMatched', name: 'literalnothingMatched');
  String literalcouldNotSignOutDescribeapierrorE(Object describeApiError) =>
      Intl.message(
        'literalcouldNotSignOutDescribeapierrorE',
        name: 'literalcouldNotSignOutDescribeapierrorE',
        args: [describeApiError],
      );
  String get literalnoDidYet =>
      Intl.message('literalnoDidYet', name: 'literalnoDidYet');
  String get literalpasswordLogin =>
      Intl.message('literalpasswordLogin', name: 'literalpasswordLogin');
  String get literalmutedAndBlockedAccounts => Intl.message(
        'literalmutedAndBlockedAccounts',
        name: 'literalmutedAndBlockedAccounts',
      );
  String get literalfontSize =>
      Intl.message('literalfontSize', name: 'literalfontSize');
  String get literalpushNotifications => Intl.message(
        'literalpushNotifications',
        name: 'literalpushNotifications',
      );
  String get literaldataSaver =>
      Intl.message('literaldataSaver', name: 'literaldataSaver');
  String get literalcontactSupport =>
      Intl.message('literalcontactSupport', name: 'literalcontactSupport');
  String get literalsendFeedback =>
      Intl.message('literalsendFeedback', name: 'literalsendFeedback');
  String get literalappLanguage =>
      Intl.message('literalappLanguage', name: 'literalappLanguage');
  String get literalprimaryLanguage =>
      Intl.message('literalprimaryLanguage', name: 'literalprimaryLanguage');
  String get literalcontentLanguages =>
      Intl.message('literalcontentLanguages', name: 'literalcontentLanguages');
  String literalremoveLanguageEnglishname(Object language) => Intl.message(
        'literalremoveLanguageEnglishname',
        name: 'literalremoveLanguageEnglishname',
        args: [language],
      );
  String literalsentItIsReportFiledNumber(Object filed) => Intl.message(
        'literalsentItIsReportFiledNumber',
        name: 'literalsentItIsReportFiledNumber',
        args: [filed],
      );
  String get literalfeedbackCannotBeSentRightNow => Intl.message(
        'literalfeedbackCannotBeSentRightNow',
        name: 'literalfeedbackCannotBeSentRightNow',
      );
  String get literalwhatYouDidWhatYouExpectedWhatHappened => Intl.message(
        'literalwhatYouDidWhatYouExpectedWhatHappened',
        name: 'literalwhatYouDidWhatYouExpectedWhatHappened',
      );
  String literalverificationFailedDescribeapierrorE(Object describeApiError) =>
      Intl.message(
        'literalverificationFailedDescribeapierrorE',
        name: 'literalverificationFailedDescribeapierrorE',
        args: [describeApiError],
      );
  String get literalverificationCodeResent => Intl.message(
        'literalverificationCodeResent',
        name: 'literalverificationCodeResent',
      );
  String get literalverifyEmail =>
      Intl.message('literalverifyEmail', name: 'literalverifyEmail');
  String get literalresendCode =>
      Intl.message('literalresendCode', name: 'literalresendCode');
  String get literalremoveThisConversation => Intl.message(
        'literalremoveThisConversation',
        name: 'literalremoveThisConversation',
      );
  String get literalmutedYouWillNotBeNotified => Intl.message(
        'literalmutedYouWillNotBeNotified',
        name: 'literalmutedYouWillNotBeNotified',
      );
  String get literalblockThisAccount =>
      Intl.message('literalblockThisAccount', name: 'literalblockThisAccount');
  String get literalyouAreSignedOut =>
      Intl.message('literalyouAreSignedOut', name: 'literalyouAreSignedOut');
  String get literalcouldNotLoadThisConversation => Intl.message(
        'literalcouldNotLoadThisConversation',
        name: 'literalcouldNotLoadThisConversation',
      );
  String get literalsaySomething =>
      Intl.message('literalsaySomething', name: 'literalsaySomething');
  String get literalcopyText =>
      Intl.message('literalcopyText', name: 'literalcopyText');
  String get literaldoNotReply =>
      Intl.message('literaldoNotReply', name: 'literaldoNotReply');
  String get literalremoveFromSaved =>
      Intl.message('literalremoveFromSaved', name: 'literalremoveFromSaved');
  String get literalturnSoundOn =>
      Intl.message('literalturnSoundOn', name: 'literalturnSoundOn');
  String get literalturnSoundOff =>
      Intl.message('literalturnSoundOff', name: 'literalturnSoundOff');
  String get literalthatLinkIsNotOneThisCanOpen => Intl.message(
        'literalthatLinkIsNotOneThisCanOpen',
        name: 'literalthatLinkIsNotOneThisCanOpen',
      );
  String get literalnoBrowserOnThisDeviceTookThatLink => Intl.message(
        'literalnoBrowserOnThisDeviceTookThatLink',
        name: 'literalnoBrowserOnThisDeviceTookThatLink',
      );
  String get literalopenReply =>
      Intl.message('literalopenReply', name: 'literalopenReply');
  String literalindex1(Object index) =>
      Intl.message('literalindex1', name: 'literalindex1', args: [index]);
  String literalfirstyearIndex(Object _firstYear) => Intl.message(
        'literalfirstyearIndex',
        name: 'literalfirstyearIndex',
        args: [_firstYear],
      );
  String get literalgifsAreNotSetUp =>
      Intl.message('literalgifsAreNotSetUp', name: 'literalgifsAreNotSetUp');
  String get literalcouldNotLoadGifs =>
      Intl.message('literalcouldNotLoadGifs', name: 'literalcouldNotLoadGifs');
  String get literalnothingFound =>
      Intl.message('literalnothingFound', name: 'literalnothingFound');
  String get literalthatGifCouldNotBeDownloaded => Intl.message(
        'literalthatGifCouldNotBeDownloaded',
        name: 'literalthatGifCouldNotBeDownloaded',
      );
  String get literaladdAnInterest =>
      Intl.message('literaladdAnInterest', name: 'literaladdAnInterest');
  String get literalcouldNotLoadTrendingTags => Intl.message(
        'literalcouldNotLoadTrendingTags',
        name: 'literalcouldNotLoadTrendingTags',
      );
  String get literalnoTrendingTagMatchesThat => Intl.message(
        'literalnoTrendingTagMatchesThat',
        name: 'literalnoTrendingTagMatchesThat',
      );
  String get literalyouAlreadyFollowEveryTrendingTag => Intl.message(
        'literalyouAlreadyFollowEveryTrendingTag',
        name: 'literalyouAlreadyFollowEveryTrendingTag',
      );
  String literalremoveLabel(Object label) => Intl.message(
        'literalremoveLabel',
        name: 'literalremoveLabel',
        args: [label],
      );
  String literaladdLabelAsATab(Object label) => Intl.message(
        'literaladdLabelAsATab',
        name: 'literaladdLabelAsATab',
        args: [label],
      );
  String get literalcouldNotSearch =>
      Intl.message('literalcouldNotSearch', name: 'literalcouldNotSearch');
  String get literalwhoDoYouWantToTag => Intl.message(
        'literalwhoDoYouWantToTag',
        name: 'literalwhoDoYouWantToTag',
      );
  String get literalnobodyFound =>
      Intl.message('literalnobodyFound', name: 'literalnobodyFound');
  String get literalshowPassword =>
      Intl.message('literalshowPassword', name: 'literalshowPassword');
  String get literalhidePassword =>
      Intl.message('literalhidePassword', name: 'literalhidePassword');
  String get literaltranslatePost =>
      Intl.message('literaltranslatePost', name: 'literaltranslatePost');
  String get literalcopyPostText =>
      Intl.message('literalcopyPostText', name: 'literalcopyPostText');
  String get literalcopyLinkToPost =>
      Intl.message('literalcopyLinkToPost', name: 'literalcopyLinkToPost');
  String get literalshowMorePostsLikeThis => Intl.message(
        'literalshowMorePostsLikeThis',
        name: 'literalshowMorePostsLikeThis',
      );
  String get literalnotInterestedInThis => Intl.message(
        'literalnotInterestedInThis',
        name: 'literalnotInterestedInThis',
      );
  String get literalhidesItAndTellsUsToShowFewerLikeIt => Intl.message(
        'literalhidesItAndTellsUsToShowFewerLikeIt',
        name: 'literalhidesItAndTellsUsToShowFewerLikeIt',
      );
  String get literalhideThisPost =>
      Intl.message('literalhideThisPost', name: 'literalhideThisPost');
  String get literalmuteThisThread =>
      Intl.message('literalmuteThisThread', name: 'literalmuteThisThread');
  String get literalstopSeeingThisPostAndRepliesToIt => Intl.message(
        'literalstopSeeingThisPostAndRepliesToIt',
        name: 'literalstopSeeingThisPostAndRepliesToIt',
      );
  String get literalmuteWordsOrTags =>
      Intl.message('literalmuteWordsOrTags', name: 'literalmuteWordsOrTags');
  String get literalviewersLikesSavesAndComments => Intl.message(
        'literalviewersLikesSavesAndComments',
        name: 'literalviewersLikesSavesAndComments',
      );
  String get literalwhoCanReply =>
      Intl.message('literalwhoCanReply', name: 'literalwhoCanReply');
  String get literaldeletePost =>
      Intl.message('literaldeletePost', name: 'literaldeletePost');
  String literalmuteAuthor(Object author) => Intl.message(
        'literalmuteAuthor',
        name: 'literalmuteAuthor',
        args: [author],
      );
  String literalblockAuthor(Object author) => Intl.message(
        'literalblockAuthor',
        name: 'literalblockAuthor',
        args: [author],
      );
  String get literalreportPost =>
      Intl.message('literalreportPost', name: 'literalreportPost');
  String literalreportAuthor(Object author) => Intl.message(
        'literalreportAuthor',
        name: 'literalreportAuthor',
        args: [author],
      );
  String get literalthatDidNotGoThroughTryAgain => Intl.message(
        'literalthatDidNotGoThroughTryAgain',
        name: 'literalthatDidNotGoThroughTryAgain',
      );
  String literalblockAuthor2(Object author) => Intl.message(
        'literalblockAuthor2',
        name: 'literalblockAuthor2',
        args: [author],
      );
  String get literalshowResults =>
      Intl.message('literalshowResults', name: 'literalshowResults');
  String literallabelDate(Object label) =>
      Intl.message('literallabelDate', name: 'literallabelDate', args: [label]);
  String get literalshareVia =>
      Intl.message('literalshareVia', name: 'literalshareVia');
  String get literalhandItToAnotherApp => Intl.message(
        'literalhandItToAnotherApp',
        name: 'literalhandItToAnotherApp',
      );
  String get literalshareWithAQuote =>
      Intl.message('literalshareWithAQuote', name: 'literalshareWithAQuote');
  String get literalpostItWithYourOwnWordsAboveIt => Intl.message(
        'literalpostItWithYourOwnWordsAboveIt',
        name: 'literalpostItWithYourOwnWordsAboveIt',
      );
  String get literalsavedPosts =>
      Intl.message('literalsavedPosts', name: 'literalsavedPosts');
  String get literallikedPosts =>
      Intl.message('literallikedPosts', name: 'literallikedPosts');
  String literalstoriesRibbonStoriesLengthItems(Object stories) => Intl.message(
        'literalstoriesRibbonStoriesLengthItems',
        name: 'literalstoriesRibbonStoriesLengthItems',
        args: [stories],
      );
  String get literalwhatYouPostIsYours => Intl.message(
        'literalwhatYouPostIsYours',
        name: 'literalwhatYouPostIsYours',
      );
  String get literalwhatKyronKeeps =>
      Intl.message('literalwhatKyronKeeps', name: 'literalwhatKyronKeeps');
  String get literalhowToBehave =>
      Intl.message('literalhowToBehave', name: 'literalhowToBehave');
  String literalcloseTabLabel(Object tab) => Intl.message(
        'literalcloseTabLabel',
        name: 'literalcloseTabLabel',
        args: [tab],
      );
  String get literal1PageOpen =>
      Intl.message('literal1PageOpen', name: 'literal1PageOpen');
  String literalcountPagesOpen(Object count) => Intl.message(
        'literalcountPagesOpen',
        name: 'literalcountPagesOpen',
        args: [count],
      );
  String get literalstopLoading =>
      Intl.message('literalstopLoading', name: 'literalstopLoading');
  String get literalshareThisPage =>
      Intl.message('literalshareThisPage', name: 'literalshareThisPage');
  String literalnoAppOnThisDeviceOpensUriSchemeLinks(Object uri) =>
      Intl.message(
        'literalnoAppOnThisDeviceOpensUriSchemeLinks',
        name: 'literalnoAppOnThisDeviceOpensUriSchemeLinks',
        args: [uri],
      );
  String get literalcloseTheBrowser =>
      Intl.message('literalcloseTheBrowser', name: 'literalcloseTheBrowser');
  String get literalcloseAllPages =>
      Intl.message('literalcloseAllPages', name: 'literalcloseAllPages');
  String get literalremoveThisPoll =>
      Intl.message('literalremoveThisPoll', name: 'literalremoveThisPoll');
  String get literalremoveThisAnswer =>
      Intl.message('literalremoveThisAnswer', name: 'literalremoveThisAnswer');
  String get literalstartRecording =>
      Intl.message('literalstartRecording', name: 'literalstartRecording');
  String get literalrecordAgain =>
      Intl.message('literalrecordAgain', name: 'literalrecordAgain');
  String literallabelCount(Object label, Object count) => Intl.message(
        'literallabelCount',
        name: 'literallabelCount',
        args: [label, count],
      );

  String get home => Intl.message('home', name: 'home');
  String get explore => Intl.message('explore', name: 'explore');
  String get communities => Intl.message('communities', name: 'communities');
  String get messages => Intl.message('messages', name: 'messages');
  String get languages => Intl.message('languages', name: 'languages');
  String get selectAppLanguage =>
      Intl.message('selectAppLanguage', name: 'selectAppLanguage');
  String get selectPrimaryLanguage =>
      Intl.message('selectPrimaryLanguage', name: 'selectPrimaryLanguage');
  String get selectContentLanguages =>
      Intl.message('selectContentLanguages', name: 'selectContentLanguages');
  String get kyronWordsStillBeingTranslated =>
      Intl.message('kyronWordsStillBeingTranslated',
          name: 'kyronWordsStillBeingTranslated');
  String get hashtagsEmptyDetail =>
      Intl.message('hashtagsEmptyDetail', name: 'hashtagsEmptyDetail');
  String get topicsEmptyDetail =>
      Intl.message('topicsEmptyDetail', name: 'topicsEmptyDetail');
  String get peopleEmptyDetail =>
      Intl.message('peopleEmptyDetail', name: 'peopleEmptyDetail');
  String get communitiesEmptyDetail =>
      Intl.message('communitiesEmptyDetail', name: 'communitiesEmptyDetail');
  String get messagesCaughtUp =>
      Intl.message('messagesCaughtUp', name: 'messagesCaughtUp');
  String get messagesNoMessages =>
      Intl.message('messagesNoMessages', name: 'messagesNoMessages');
  String get notificationLikesDetail =>
      Intl.message('notificationLikesDetail', name: 'notificationLikesDetail');
  String get notificationRepliesDetail =>
      Intl.message('notificationRepliesDetail',
          name: 'notificationRepliesDetail');
  String get notificationFollowersDetail =>
      Intl.message('notificationFollowersDetail',
          name: 'notificationFollowersDetail');
  String get notificationRepostsDetail =>
      Intl.message('notificationRepostsDetail',
          name: 'notificationRepostsDetail');
  String get notificationEmptyDetail =>
      Intl.message('notificationEmptyDetail', name: 'notificationEmptyDetail');
  String get gettingHelp => Intl.message('gettingHelp', name: 'gettingHelp');
  String get send => Intl.message('send', name: 'send');
  String get close => Intl.message('close', name: 'close');
  String get search => Intl.message('search', name: 'search');
  String get settings => Intl.message('settings', name: 'settings');
  String get menu => Intl.message('menu', name: 'menu');
  String get clear => Intl.message('clear', name: 'clear');
  String get manage => Intl.message('manage', name: 'manage');
  String get join => Intl.message('join', name: 'join');
  String get video => Intl.message('video', name: 'video');

  String get contentLanguagesNotFilteringYet =>
      Intl.message('contentLanguagesNotFilteringYet',
          name: 'contentLanguagesNotFilteringYet');
  String get addMoreLanguages =>
      Intl.message('addMoreLanguages', name: 'addMoreLanguages');
  String get translationNotBuiltYet =>
      Intl.message('translationNotBuiltYet', name: 'translationNotBuiltYet');
  String get supportEarlyExplanation =>
      Intl.message('supportEarlyExplanation', name: 'supportEarlyExplanation');
  String get supportInboxNotYet =>
      Intl.message('supportInboxNotYet', name: 'supportInboxNotYet');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  List<Locale> get supportedLocales => const [
        Locale('en'),
        Locale('es'),
        Locale('ja'),
        Locale('ko'),
        Locale('zh')
      ];

  @override
  bool isSupported(Locale locale) =>
      ['en', 'es', 'ja', 'ko', 'zh'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
