name: Bug Report
description: File a bug report
title: "[bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: 1. ... 2. ... 3. ...
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - iOS
        - Android
        - Web
        - Backend
